version: "3.5"

services:
  ########################################################
  ### Loaders
  ########################################################

  loader-basic:
    container_name: loader-basic
    hostname: loader-basic
    restart: always
    image: fernandodumont/acme-flights-loaders:latest
    env_file: ./config/appd/controller.env
    volumes:
      - ./config/loader/base-load.yml:/app/config/base-load.yml
    depends_on:
      - web-frontend
      - api-manager
      - ws-services

  ########################################################
  ### Web Front End
  ########################################################

  web-frontend:
    container_name: web-frontend
    hostname: web-frontend
    restart: always
    image: fernandodumont/acme-flights-web-frontend:latest
    env_file: ./config/appd/controller.env
    expose:
      - 8090
    ports:
      - 8090:80
    volumes:
      - ./config/web-frontend/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./config/web-frontend/env.js:/usr/share/nginx/html/assets/env.js
      - ./config/web-frontend/appd.js:/usr/share/nginx/html/assets/appd.js
    depends_on:
      - api-manager

  ########################################################
  ### Java
  ########################################################

  api-manager:
    container_name: api-manager
    hostname: api-manager
    restart: always
    image: fernandodumont/acme-flights-java-services:latest
    expose:
      - 8080
    ports:
      - 8080:8080
    env_file: ./config/appd/controller.env
    environment:
      - JAVA_TOOL_OPTIONS=-javaagent:/opt/appdynamics/java-agent/javaagent.jar
      - APPDYNAMICS_AGENT_TIER_NAME=api-manager
      - APPDYNAMICS_AGENT_NODE_NAME=api-manager-1
    volumes:
      - java-agent:/opt/appdynamics/java-agent/
    depends_on:
      - auth-services
      - flight-services
      - ticket-services
      - track-services
      - ws-services

  auth-services:
    container_name: auth-services
    hostname: auth-services
    restart: always
    image: fernandodumont/acme-flights-java-services:latest
    env_file: ./config/appd/controller.env
    environment:
      - JAVA_TOOL_OPTIONS=-javaagent:/opt/appdynamics/java-agent/javaagent.jar
      - APPDYNAMICS_AGENT_TIER_NAME=auth-services
      - APPDYNAMICS_AGENT_NODE_NAME=auth-services-1
    volumes:
      - java-agent:/opt/appdynamics/java-agent/
    depends_on:
      - mongo-acme
      - mysql-acme
      - activemq-acme
      - ldap-acme

  flight-services:
    container_name: flight-services
    hostname: flight-services
    restart: always
    image: fernandodumont/acme-flights-java-services:latest
    env_file: ./config/appd/controller.env
    environment:
      - JAVA_TOOL_OPTIONS=-javaagent:/opt/appdynamics/java-agent/javaagent.jar
      - APPDYNAMICS_AGENT_TIER_NAME=flight-services
      - APPDYNAMICS_AGENT_NODE_NAME=flight-services-1
    volumes:
      - java-agent:/opt/appdynamics/java-agent/
    depends_on:
      - mongo-acme
      - mysql-acme
      - activemq-acme
      - ldap-acme

  ticket-services:
    container_name: ticket-services
    hostname: ticket-services
    restart: always
    image: fernandodumont/acme-flights-java-services:latest
    env_file: ./config/appd/controller.env
    environment:
      - JAVA_TOOL_OPTIONS=-javaagent:/opt/appdynamics/java-agent/javaagent.jar
      - APPDYNAMICS_AGENT_TIER_NAME=ticket-services
      - APPDYNAMICS_AGENT_NODE_NAME=ticket-services-1
    volumes:
      - java-agent:/opt/appdynamics/java-agent/
    depends_on:
      - mongo-acme
      - mysql-acme
      - activemq-acme
      - ldap-acme

  track-services:
    container_name: track-services
    hostname: track-services
    restart: always
    image: fernandodumont/acme-flights-java-services:latest
    env_file: ./config/appd/controller.env
    environment:
      - JAVA_TOOL_OPTIONS=-javaagent:/opt/appdynamics/java-agent/javaagent.jar
      - APPDYNAMICS_AGENT_TIER_NAME=track-services
      - APPDYNAMICS_AGENT_NODE_NAME=track-services-1
    volumes:
      - java-agent:/opt/appdynamics/java-agent/
    depends_on:
      - mongo-acme
      - mysql-acme
      - activemq-acme
      - ldap-acme

  ws-services:
    container_name: ws-services
    hostname: ws-services
    restart: always
    image: fernandodumont/acme-flights-ws-services:latest
    env_file: ./config/appd/controller.env
    environment:
      - JAVA_TOOL_OPTIONS=-javaagent:/opt/appdynamics/java-agent/javaagent.jar
      - APPDYNAMICS_AGENT_TIER_NAME=ws-services
      - APPDYNAMICS_AGENT_NODE_NAME=ws-services-1
    volumes:
      - java-agent:/opt/appdynamics/java-agent/
    depends_on:
      - mongo-acme
      - mysql-acme
      - activemq-acme
      - ldap-acme

  ########################################################
  ### Mock Services
  ########################################################
  sap-services:
    container_name: sap-services
    hostname: sap-services
    restart: always
    image: fernandodumont/acme-flights-java-services:latest

  finance-services:
    container_name: finance-services
    hostname: finance-services
    restart: always
    image: fernandodumont/acme-flights-java-services:latest

  ########################################################
  ### Databases and other backends
  ########################################################

  mongo-acme:
    image: fernandodumont/acme-flights-mongodb:latest
    container_name: mongo-acme
    hostname: mongo-acme
    restart: always
    expose:
      - 27017
    ports:
      - 27017:27017

  mysql-acme:
    image: fernandodumont/acme-flights-mysqldb:latest
    container_name: mysql-acme
    hostname: mysql-acme
    restart: always
    expose:
      - 3306
    ports:
      - 3306:3306

  activemq-acme:
    image: fernandodumont/acme-flights-activemq:latest
    container_name: activemq-acme
    hostname: activemq-acme
    restart: always
    expose:
      - 8161
      - 61616
    ports:
      - 8161:8161
      - 61616:61616

  ldap-acme:
    image: bitnami/openldap:latest
    container_name: ldap-acme
    hostname: ldap-acme
    restart: always
    environment:
      - LDAP_ADMIN_USERNAME=admin
      - LDAP_ADMIN_PASSWORD=admin1
      - LDAP_USERS=acmeflight
      - LDAP_PASSWORDS=acmeflight1
    expose:
      - 1389
      - 1636
    ports:
      - 1389:1389
      - 1636:1636

  ########################################################
  ### AppDynamics
  ########################################################

  java-agent:
    container_name: java-agent
    hostname: java-agent
    image: appdynamics/java-agent:latest
    volumes:
      - java-agent:/opt/appdynamics

  machine-agent:
    container_name: machine-agent
    hostname: machine-agent
    image: appdynamics/machine-agent-analytics:latest
    env_file: ./config/appd/controller.env
    environment:
      - APPDYNAMICS_SIM_ENABLED=true
      - APPDYNAMICS_DOCKER_ENABLED=true
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - /:/hostroot:ro
    expose:
      - 9090

volumes:
  java-agent:
