version: "3.5"

services:
  ########################################################
  ### Loaders
  ########################################################

  loader-async:
    container_name: loader-async
    hostname: loader-async
    restart: always
    image: fernandodumont/acme-flights-loaders:latest
    environment:
      - ENABLE_ASYNC_LOAD=1
    env_file: ../config/appd/controller.env
    volumes:
      - ../config/loader/async-front.yml:/app/config/async-front.yml
    depends_on:
      async-front:
        condition: service_healthy
    networks:
      - async-app-net

  ########################################################
  ### Front
  ########################################################

  async-front:
    container_name: async-front
    hostname: async-front
    restart: always
    image: fernandodumont/async-front:latest
    expose:
      - 8086
    ports:
      - 8086:8086
    env_file: ../config/appd/controller.env
    environment:
      - JAVA_TOOL_OPTIONS=-javaagent:/opt/appdynamics/java-agent/javaagent.jar
      - APPDYNAMICS_AGENT_TIER_NAME=async-front
      - APPDYNAMICS_AGENT_NODE_NAME=async-front-1
      - APPDYNAMICS_AGENT_APPLICATION_NAME=ASYNC_APP
    volumes:
      - java-agent-async:/opt/appdynamics/java-agent/
    depends_on:
      async-back:
        condition: service_healthy
    networks:
      - async-app-net

  ########################################################
  ### Back
  ########################################################

  async-back:
    container_name: async-back
    hostname: async-back
    restart: always
    image: fernandodumont/async-back:latest
    ports:
      - 8087:8087
    env_file: ../config/appd/controller.env
    environment:
      - JAVA_TOOL_OPTIONS=-javaagent:/opt/appdynamics/java-agent/javaagent.jar
      - APPDYNAMICS_AGENT_TIER_NAME=async-back
      - APPDYNAMICS_AGENT_NODE_NAME=async-back-1
      - APPDYNAMICS_AGENT_APPLICATION_NAME=ASYNC_APP
    volumes:
      - java-agent-async:/opt/appdynamics/java-agent/
    depends_on:
      - mongo-async
    networks:
      - async-app-net

  ########################################################
  ### Databases and other backends
  ########################################################

  mongo-async:
    image: mongo:latest
    container_name: mongo-async
    hostname: mongo-async
    command: mongod --port 27018
    restart: always
    ports:
      - 27018:27018
    networks:
      - async-app-net

  ########################################################
  ### AppDynamics
  ########################################################

  java-agent-async:
    container_name: java-agent-async
    hostname: java-agent-async
    image: appdynamics/java-agent:latest
    volumes:
      - java-agent-async:/opt/appdynamics

volumes:
  java-agent-async:

networks:
  async-app-net:
