useCases:
  - {
      "urlCheck": "/api/useCase/UC_CALL_MANY_TICKET_CLASS/api-manager",
      "urlRun": "/api/ticketClasses",
      "waitTime": 500,
      "count": 1,
    }
  - {
      "urlCheck": "/api/useCase/UC_AIRLINE_DETAIL_TIMEOUT/flight-services",
      "urlRun": "/api/airportDetails/BSB",
      "waitTime": 50,
      "count": 5,
    }
  - {
      "urlCheck": "/api/useCase/UC_ADD_TRACK_SLEEP/track-services",
      "urlRun": "/api/searchBookFlight/no@email.com",
      "waitTime": 2000,
      "count": 2,
    }
  - {
      "urlCheck": "/api/useCase/UC_ERROR_INSERT_QUERY/track-services",
      "urlRun": "/api/track/error-db/no@email.com",
      "waitTime": 2000,
      "count": 2,
    }
  - {
      "urlCheck": "/api/useCase/UC_SPIKE_TICKET_CLASS/flight-services",
      "urlRun": "/api/ticketClasses",
      "waitTime": 100,
      "count": 1,
    }
  - {
      "urlCheck": "/api/useCase/UC_ONLY_ONE_BT/api-manager",
      "urlRun": "/api/airlines",
      "waitTime": 30000,
      "count": 10,
    }
  - {
      "urlCheck": "/api/useCase/UC_STOP_LOADER_BASIC/api-manager",
    }    
